trigger:
- main  # or your branch name

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: pauljaison606/my-node-app
 
steps: 
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    containerRegistry: 'docker-hub-sc'  # Docker Hub service connection name
    repository: '$(imageName)'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest

- task: Docker@2
  displayName: 'Push Docker Image'
  inputs:
    containerRegistry: 'docker-hub-sc'  
    repository: '$(imageName)'
    command: 'push'
    tags: |
      latest
